### ISSUE TITLE
Python: ModuleNotFoundError: No module named '_socket' on WSL2

### ISSUE THREAD

**Issue by darvesh** [metacall/distributable#6]
**System information:** 
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 5.4.72-microsoft-standard-WSL2

Pastebin: https://b.darve.sh/LV0
![image](https://user-images.githubusercontent.com/22394081/125170184-53794800-e1cb-11eb-965a-85eb55504f96.png)

![image](https://user-images.githubusercontent.com/22394081/125170233-9cc99780-e1cb-11eb-8908-dae99e28dc41.png)

![image](https://user-images.githubusercontent.com/22394081/125170275-cf739000-e1cb-11eb-9544-3f802833d45a.png)

`find /gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2 -regex "socket"` returns no result.

**Comment by viferga** [comment]
Solved: https://github.com/metacall/install/commit/3a31ab40b6e089da48afdafecd0fc8bc0e70b41c
